services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/home/user/ssl:ro
      - ./nginx/validation:/home/user/validation:ro
    restart: always
    platform: linux/amd64

  frontend:
    image: forum-frontend
    build:
      context: ./client
    restart: always
    platform: linux/amd64

  backend:
    image: forum-backend
    build:
      context: server
    depends_on:
      - postgres
    restart: always
    platform: linux/amd64

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    platform: linux/amd64

volumes:
  pgdata:
