services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  frontend:
    image: forum-frontend
    build:
      context: nuxt-client
    restart: always

  backend:
    image: forum-backend
    build:
      context: server
    depends_on:
      - postgres
    volumes:
      - ./data/files:/files
    restart: always

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data
    restart: always
