CREATE TABLE
  posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE,
    author_id BIGINT,
    post_id BIGINT,
    PRIMARY key (id)
  );

CREATE TABLE
  roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(10) NOT NULL UNIQUE,
    PRIMARY key (id)
  );

CREATE TABLE
  user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
  );

CREATE TABLE
  users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    PRIMARY key (id)
  );

ALTER TABLE if EXISTS posts ADD FOREIGN key (author_id) REFERENCES users;

ALTER TABLE if EXISTS posts ADD FOREIGN key (post_id) REFERENCES posts;

ALTER TABLE if EXISTS user_roles ADD FOREIGN key (role_id) REFERENCES roles;

ALTER TABLE if EXISTS user_roles ADD FOREIGN key (user_id) REFERENCES users;