CREATE TABLE
  posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    author_id BIGINT,
    root_post_id BIGINT,
    post_id BIGINT,
    PRIMARY KEY (id)
  );

CREATE TABLE
  roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(10) NOT NULL UNIQUE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
  );

CREATE TABLE
  users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(16) UNIQUE,
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
  );

ALTER TABLE if EXISTS posts ADD FOREIGN KEY (author_id) REFERENCES users;

ALTER TABLE if EXISTS posts ADD FOREIGN KEY (root_post_id) REFERENCES posts;

ALTER TABLE if EXISTS posts ADD FOREIGN KEY (post_id) REFERENCES posts;

ALTER TABLE if EXISTS user_roles ADD FOREIGN KEY (role_id) REFERENCES roles;

ALTER TABLE if EXISTS user_roles ADD FOREIGN KEY (user_id) REFERENCES users;

INSERT INTO roles (name) VALUES ('admin');

INSERT INTO roles (name) VALUES ('user');
